name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - run: cd apps/site-1 && pnpm install --frozen-lockfile
      - run: cd apps/site-1 && pnpm build
      - uses: actions/deploy-pages@v4
        with:
          folder: apps/site-1/dist
